app/assets/javascripts/users/show.js.coffee
app/views/users/show.html.erb
test/functional/data_sets_controller_test.rb
test/integration/small_page_test.rb

Addresses #1795 
And while I was at it, I fixed our tests.  They no longer have extremely long names that overflow the PASS/FAIL/ERROR column and no longer contain deprecated window re-sizing code :+1:

Fixed issue of clicking Liked Projects on user page not doing anything

---

app/views/shared/_media_objects_view.html.erb

Reverts PR #1840 
Adds featured label back as discussed in #1876.

Reverting PR 1840 - Hiding featured media label on visualizations

---

test/CSVs/Konqi.svg
test/fixtures/contrib_keys.yml
test/fixtures/media_objects.yml
test/fixtures/projects.yml
test/functional/media_objects_controller_test.rb
test/functional/projects_controller_test.rb
test/functional/visualizations_controller_test.rb
test/helpers/fields_helper_test.rb
test/integration/upload_media_test.rb
test/test_helper.rb
test/unit/visualization_test.rb

Added some tests to increase code coverage throughout the site.  I specifically did not test the Report a Bug feature, since I saw tests for it were already in the pipeline.  @jaypoulz , this increases code coverage to 89.88% :smile:

New tests to increase code coverage

---

app/assets/javascripts/visualizations/highvis/scatter.coffee

Title pretty much says it all.  Addresses issue #1893

Regressions work with multiple fields being viewed on the y axis.

---

app/helpers/application_helper.rb

Changes made:
- if viewing one data set in a project, display its title
- if viewing multiple data sets in a project, display "Showing Multiple Data Sets" (similar to what appears on the page itself)
- if viewing a saved vis, display its title
Addresses #1834

Gave the title bar more meaning

---

app/views/home/contact.html.erb

Added 2015 to jakes BS receive

---

app/views/home/api_v1.html.erb

fixed typo in api docs

---

lib/assets/javascripts/info_edit.js.coffee

Addresses #1669 
Thanks to @asalani93 for basically helping with 99% of the work here :smile_cat: 
Can't wait to reclaim *half* of my Ubuntu partition back that is currently being eaten by an IE-Win7-VM.

IE is bad and should feel bad.  Changing project titles works

---

app/views/home/api_v1.html.erb

removes unused title paramater from append api call

---

app/assets/javascripts/users/show.js.coffee

Fixed indentation - No results doesn't always appear in pane now, whoops

---

app/views/home/contact.html.erb

Added Jim's degrees, as per request of Jim.

Fixes Jim in contact page

---

app/controllers/api/v1/projects_controller.rb
app/views/home/api_v1.html.erb
test/integration/api_v1_test.rb

add key api call had two parameters for the project id

---

app/views/visualizations/index.html.erb

Clicking vis image links to that vis

---

app/models/data_set.rb
test/integration/api_v1_test.rb

@jaypoulz 
I'm not sure if there is a bug made for this. I can't find it if there is.

Add owner and key to data set hash

---

Gemfile
Gemfile.lock
app/controllers/users_controller.rb
app/views/users/new.html.erb
config/initializers/recaptcha.rb

Adding recaptcha v2
Fixing problems with user creation errors
#2012

Recaptcha v2

---

app/views/users/show.html.erb
test/integration/show_user_test.rb

Switched tab order

---

app/views/projects/_form.html.erb

on top is 2 words under Map Layer section now.

Copyedit in projects#edit

---

Gemfile
app/assets/javascripts/visualizations/highvis/map.coffee
app/assets/stylesheets/application.css.scss

#1563
@jaypoulz 
I tried using a number as an indicator, but I thought that it looked much better without any type of indicator. I can put it back if you think it looks too plain.

View Pictures on Map Vis

---

app/assets/stylesheets/application.css.scss

Can see pointer cursor on box headers now

---

app/assets/javascripts/shared/media_objects_view.js.coffee
app/controllers/testing_controller.rb
app/views/testing/publish.html.erb
lib/assets/javascripts/info_edit.js.coffee
vendor/assets/javascripts/slickgrid-editors/slickgrid-time.coffee

Removed console.logs and puts

---

app/assets/javascripts/visualizations/highvis/pie.coffee

Addresses #2050 as per request of @jdalphon

Pie chart titles no longer backwards

---

app/assets/stylesheets/application.css.scss
lib/assets/javascripts/info_edit.js.coffee

Fixing data set rename error.

---

app/assets/javascripts/users/show.js.coffee

wonky indentation breaking logged out

---

app/assets/javascripts/visualizations/highvis/map.coffee
app/assets/stylesheets/application.css.scss

Revert "View Pictures on Map Vis"

---

app/assets/javascripts/visualizations/highvis/histogram.coffee

Fixes the issue Sam Michalka observed on live. 
@jaypoulz

Added default value of zero for min/max operations on lists in Histogram.

---

lib/file_uploader.rb

Addresses #2062 
Additionally, will match to Timestamp if the data is nil but the header contains 'time'

CSV templates default to *number* if data are nil

---

app/controllers/media_objects_controller.rb

Media whitelist checks proper extension and is case insensitive

---

app/views/layouts/application.html.erb
app/views/projects/index.html.erb
app/views/shared/_project_box.html.erb
app/views/shared/_vis_box.html.erb
app/views/visualizations/index.html.erb
test/integration/summernote_mo_test.rb

Addresses #2059
:cake:   :goat:

Vis and project index page boxes are now more consistent

---

app/views/projects/show.html.erb

Do you think it looks better?
Addresses #2045

Resized key image

---

app/views/shared/_media_objects_view.html.erb

Addresses #1962 
Edit | Delete always stay on one line regardless of the browser window size.

Fixed media controls responsiveness

---

app/assets/javascripts/visualizations/highvis/map.coffee
app/assets/stylesheets/application.css.scss

Images on map vis

---

app/controllers/api/v1/projects_controller.rb
test/integration/api_v1_test.rb

Report error for trying to create a key through API if it exists

---

app/assets/javascripts/users/show.js.coffee
app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb
app/assets/javascripts/visualizations/highvis/savedVis.coffee
app/controllers/sessions_controller.rb
app/views/sessions/permissions.js.erb
config/routes.rb
test/functional/sessions_controller_test.rb

Also added back the ajax.error from #2058. This time, it's indented under the user show page. Also, the previous call that was causing it to error out has been patched to work more nicely.
The diff is weird because github doesn't understand the concept of re indenting a file.

Refactored verification of login information

---

app/assets/stylesheets/visualizations.css.scss
app/views/visualizations/displayVis.html.erb

No associated issue, but implements the refresh feature that is currently sitting on live.

Added a get latest data to the regular vis page

---

app/views/projects/show.html.erb

Addresses #2086 
Also removed option to hide b/c I don't think that's ever a thing... even for admin.

Made dataset edit | delete consistent w/ media box

---

app/assets/javascripts/projects/edit_fields.js.coffee

Edit table submits on enter

---

app/assets/stylesheets/application.css.scss
app/views/layouts/_footer.html.erb
app/views/layouts/application.html.erb

New Footer.
Old footer:
New footer:
New footer on mobile:

Giving the website some shiny new shoes

---

app/views/testing/publish.html.erb

fix manual testing page

---

app/views/users/_display_contributions.html.erb

Just adding a max width to the <td> for now because this page is changing shortly. 
#2111

Temporary fix for long project names on Users/Show

---

app/views/projects/show.html.erb

Fixed data sets edit|delete controls alignment

---

app/assets/stylesheets/api.css.scss
app/views/home/api_v1.html.erb

Fix spelling mistakes and overflow.

---

app/views/testing/index.html.erb
app/views/testing/publish.html.erb
app/views/testing/review.html.erb

Clicking an issue number opens a new tab

---

app/helpers/application_helper.rb

no longer capitalize data set title in tab

---

app/assets/javascripts/visualizations/highvis/map.coffee

camera symbols on map

---

app/controllers/contrib_keys_controller.rb
app/models/contrib_key.rb
app/views/projects/_form.html.erb
app/views/projects/edit.html.erb

Better errors for when creating a key fails

---

lib/file_uploader.rb

Address #2005.
This is just a quick band-aid for supporting multiple timestamp formats.

Quick fix for timestamp field matching

---

app/assets/javascripts/visualizations/highvis/histogram.coffee
app/views/layouts/application.html.erb

Also patched histogram tooltip error

Fixed the wat (stuff that was wierd with my quick-fix PR for 2.0)

---

app/assets/javascripts/application.js
app/assets/javascripts/visualizations/highvis/bar.coffee
app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb
app/assets/javascripts/visualizations/highvis/pie.coffee
db/migrate/20150519161334_add_mean_error_bars.rb
test/fixtures/tutorials.yml
test/fixtures/visualizations.yml

Addresses #1896.  We now have error bars on bar chart.
This was added as an additional analysis type ("Mean with Error").  However, it makes no sense to show error bars on pie chart.  Therefore, I had to add a system so that different visualizations that use analysis types can have what analysis types they use be customized on a per-vis level.

Adds standard deviation error bars to bar chart

---

app/views/projects/show.html.erb

Addresses #1753.
I moved some things around and now it works.

this was a very tough bug to fix

---

app/assets/javascripts/visualizations/highvis/histogram.coffee
app/assets/javascripts/visualizations/highvis/map.coffee
app/assets/javascripts/visualizations/highvis/pie.coffee

Reworked negative number support in Map and Pie

---

app/assets/javascripts/visualizations/highvis/histogram.coffee
app/assets/javascripts/visualizations/highvis/visUtils.coffee

#2132 
Line 118 is the actual fix.

Fixed (at least one of) the freezing histogram problems

---

app/assets/javascripts/projects/index.js.coffee
app/views/projects/_filters_search.html.erb
app/views/projects/index.html.erb
app/views/visualizations/index.html.erb
test/integration/make_project_test.rb

Addresses #2143.
I made some things look different for the project search on different screen sizes.  Search bar now has a search icon instead of a button that says search.

Makes mobile view for projects index page look semi-reasonable

---

app/assets/javascripts/application.js
app/assets/javascripts/data_sets/editTable.js.coffee
app/helpers/data_sets_helper.rb
lib/file_uploader.rb
vendor/assets/javascripts/jquery.caret.js
vendor/assets/javascripts/slickgrid-editors/slickgrid-decimal.coffee
vendor/assets/javascripts/slickgrid-editors/slickgrid-location.coffee
vendor/assets/javascripts/slickgrid-editors/slickgrid-text.coffee

Addresses #2146.
There's a handful of issues that affected data set editing.  All are documented in the issue and all have been fixed.  I'm not sure if anything changed, or if the science of rivers data set was just the perfect storm for breaking data set editing.

Making the data set edit page behave

---

app/assets/stylesheets/visualizations.css.scss

fix visualizations from cutting in half on chrome 43

---

app/assets/javascripts/visualizations/highvis/bar.coffee

Adding a dark origin line to bar chart

---

app/views/projects/show.html.erb

data set search button is no longer cut off on mobile

---

app/assets/javascripts/users/show.js.coffee
app/assets/stylesheets/application.css.scss
app/assets/stylesheets/users.css.scss
app/controllers/users_controller.rb
app/views/users/_display_contributions.html.erb
app/views/users/show.html.erb
test/fixtures/projects.yml
test/integration/user_sorting_test.rb
test/test_helper.rb

Addresses #2174.
Can now sort all user contributions by title and date created, in both an ascending and descending fashion.  I'm  also pretty sure that I got which way ascending and descending go.

Sorting user contributions

---

app/assets/javascripts/visualizations/highvis/bar.coffee
app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb

Addresses #2178.
If there's anything else that needs to be changed, let me know.

Sets mean to be default analysis mode for bar chart

---

app/assets/javascripts/templates/visualizations/photo/group.hbs
app/assets/javascripts/templates/visualizations/photo/pic.hbs
app/assets/javascripts/visualizations/highvis/photos.coffee
app/assets/stylesheets/visualizations.css.scss

Addresses #2187.
You can now group and filter out photos based on what data set they are in.

Adds grouping to photo vis

---

app/assets/javascripts/visualizations/highvis/scatter.coffee

Towards #2188 
I don't know that this will allow for the vis to load completely, but it will pass these malformed objects.

Added nullity checkers to saved regressions

---

app/views/visualizations/_vis.html.erb

#2177 
Instead of "Showing Multiple Data Sets" it will now say "Showing 3 Data Sets".

Visualization title now says the number of data sets instead of "multiple"

---

app/views/visualizations/index.html.erb

Add placeholder for searching saved vises

---

app/assets/javascripts/shared/media_objects_view.js.coffee
app/controllers/visualizations_controller.rb
app/models/visualization.rb
test/integration/delete_then_feature_mo_test.rb

Addresses #2202.
Fixes the same thing, but for vis.  Adds a test.

Fix vis index crash

---

app/controllers/data_sets_controller.rb

Contributor names now appear where they should

---

app/views/shared/_project_box.html.erb

fixing assets pipeline for background image on production

fixing assets pipeline for background image on production

---

app/views/visualizations/_vis.html.erb

real number of data sets

---

app/helpers/application_helper.rb

Adds true case insensitive matching for contributor keys

---

app/controllers/visualizations_controller.rb
app/views/visualizations/index.html.erb

vis sort default by time created

---

Gemfile
Gemfile.lock

Colorpicker thing

---

Gemfile
Gemfile.lock
app/controllers/api/v1/data_sets_controller.rb
app/controllers/api/v1/fields_controller.rb
app/controllers/api/v1/media_objects_controller.rb
app/controllers/api/v1/projects_controller.rb
app/controllers/api/v1/users_controller.rb
app/controllers/api/v1/visualizations_controller.rb
app/controllers/application_controller.rb
config/application.rb

Addresses #2234.
Now using Rack CORS to allow CORS instead of whatever we had before.

Changes API to correctly handle CORS

---

app/controllers/tutorials_controller.rb
app/views/tutorials/index.html.erb

pages for tutorials

---

app/controllers/news_controller.rb
app/views/news/index.html.erb

pagination for news articles

---

app/controllers/visualizations_controller.rb

Addresses #2236.
Not sure how this worked until recently.

Saved visualizations get thumbnails again

---

app/assets/javascripts/projects/edit_fields.js.coffee
app/assets/stylesheets/fields.css.scss
app/controllers/projects_controller.rb
app/views/projects/edit_fields.html.erb

Fix style of fields while sorting

---

app/models/data_set.rb
app/models/user.rb
test/fixtures/data_sets.yml
test/integration/search_data_sets_test.rb

#2257
Previously if you searched for a
number -> data set ids
string -> titles
This pull request changes it to
number -> data set ids AND titles
string -> titles

Searching data sets with a number also searches title

---

app/assets/javascripts/projects/edit_fields.js.coffee
app/assets/stylesheets/fields.css.scss
app/controllers/projects_controller.rb
app/views/projects/edit_fields.html.erb

Revert "Fix style of fields while sorting"

---

app/assets/javascripts/visualizations/highvis/map.coffee
app/views/visualizations/_vis.html.erb

Fixes heatmaps

---

app/controllers/visualizations_controller.rb
db/schema.rb
test/fixtures/data_sets.yml
test/fixtures/fields.yml
test/fixtures/projects.yml
test/integration/map_no_data_disable_test.rb

#2262 
Fixed Map Vis so that it is correctly disabled when no location data is present.

Map vis is disabled when there isn't any location data

---

app/controllers/data_sets_controller.rb
app/controllers/sessions_controller.rb
test/integration/upload_data_test.rb

contrib name no longer shows up after logging in

---

app/views/visualizations/_vis.html.erb
test/fixtures/data_sets.yml
test/fixtures/projects.yml
test/integration/number_of_data_sets_test.rb

When you visualize 5 of the 10 data sets the visualization will now correctly say "Showing 5 Data Sets" instead of "Showing 10 Data Sets"

"Showing x data sets" -> x is now the correct number of data sets

---

app/assets/javascripts/visualizations/highvis/disabledVis.coffee
app/views/projects/edit_fields.html.erb

Better timeline errors

---

app/assets/javascripts/visualizations/highvis/pie.coffee

Fixed pie chart color bug

---

app/controllers/projects_controller.rb
test/integration/update_fields_test.rb

Set Lat, Lon, and Timestamp names correctly.

---

app/assets/javascripts/visualizations/highvis/scatter.coffee

Revert "Fixed issue ps2276 - project 891 breaks vis rendering"

---

app/assets/javascripts/visualizations/highvis/scatter.coffee

Reverts isenseDev/rSENSE#2306
I thought this was breaking the vises but it turns out it was #2282

Revert "Revert "Fixed issue ps2276 - project 891 breaks vis rendering""

---

app/assets/javascripts/visualizations/highvis/highmodifiers.coffee

Revert "Groups no longer lose capitalization in the Group By function"

---

app/assets/javascripts/visualizations/highvis/bar.coffee

#2285 The function signature changed when data filtering was introduced.

Fix mean with error

---

app/assets/javascripts/visualizations/highvis/table.coffee

Fixed Table Color Bug

---

app/assets/javascripts/visualizations/highvis/bar.coffee
app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb
app/assets/javascripts/visualizations/highvis/highmodifiers.coffee
app/assets/javascripts/visualizations/highvis/histogram.coffee
app/assets/javascripts/visualizations/highvis/map.coffee
app/assets/javascripts/visualizations/highvis/pie.coffee
app/assets/javascripts/visualizations/highvis/scatter.coffee
app/assets/javascripts/visualizations/highvis/summary.coffee
app/assets/javascripts/visualizations/highvis/table.coffee
app/controllers/visualizations_controller.rb
db/migrate/20160128175730_add_groups_to_saved_visualizations.rb

#1852  Group by Numbers (For Pie Chart Only)
#2088 Group by Contributors

Groups by Numbers and Contributors

---

app/views/data_sets/manualEntry.html.erb
test/integration/slickgrid_test.rb

#2338 Pre-populates dataset name with username/contrib name + date and time in the format (Bobby 12/30/2015 4:29pm)

Manual Entry Pre-Populate DS Name

---

app/assets/javascripts/visualizations/highvis/bar.coffee

Sort by field by default in bar chart if only one field is selected

---

app/assets/javascripts/visualizations/highvis/highmodifiers.coffee
app/assets/javascripts/visualizations/highvis/visUtils.coffee

Revert "Capitalization lost in "Group by" function"

---

Gemfile.lock
app/assets/javascripts/templates/visualizations/controls/scatter-tools.hbs
app/assets/javascripts/visualizations/highvis/scatter.coffee
app/assets/stylesheets/visualizations.css.scss
db/schema.rb

Revert "Settable min/max for axes"

---

app/assets/javascripts/visualizations/highvis/photos.coffee
db/migrate/20160128175730_add_groups_to_saved_visualizations.rb
db/schema.rb

Fixes issues with Pull Request #2337
Bugs associated are..
#1852 Group by Numbers (For Pie Chart Only)
#2088 Group by Contributors

Fixes remaining issues with new "group by" options

---

Gemfile.lock
app/assets/javascripts/templates/visualizations/controls/scatter-tools.hbs
app/assets/javascripts/visualizations/highvis/scatter.coffee
app/assets/javascripts/visualizations/highvis/timeline.coffee
app/assets/stylesheets/visualizations.css.scss
db/schema.rb

scatter axis bounds

---

README.rdoc
app/views/home/api_v1.html.erb
test/integration/base_integration_test.rb
test/integration/show_user_test.rb

This pull request adds a call to wait for the ajax to finish to eliminate the race condition. I also upped capybaras default wait time from 2 seconds to 5 seconds.

fixes race condition in show user test

---

circle.yml

Overrides circle ci so it runs "rake" instead of "rake test"

circle ci now runs rubocop instead of just "rake test"

---

app/assets/javascripts/visualizations/highvis/map.coffee
app/assets/javascripts/visualizations/highvis/scatter.coffee

Tp2334 heatmap crash

---

app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb
app/assets/javascripts/visualizations/highvis/summary.coffee

#1569
Color picker no longer appears on summary tab.

Color picker no longer appears on summary tab.

---

app/assets/javascripts/projects/edit_fields.js.coffee

#2335. Removed all counter decrements in edit_fields.js.coffee because it was pointless and caused bugs.

Time stamps fixed for issue 2335

---

.gitignore
app/controllers/passwords_controller.rb
app/views/users/pw_send_key.html.erb
config/environments/production.rb
config/routes.rb

Forgot password emails work again!

---

app/assets/javascripts/projects/edit_fields.js.coffee
app/controllers/projects_controller.rb

fixes field entry weirdness

---

app/controllers/users_controller.rb
app/views/devise/sessions/new.html.erb
app/views/users/show.html.erb

User page works again when not signed out

---

app/controllers/users_controller.rb

Contributions on user page will render if not signed in

---

app/views/devise/sessions/new.html.erb

link goes to correct news article

---

app/controllers/application_controller.rb

Can create github issues again

---

app/helpers/application_helper.rb

#2393 
` return false if current_user.nil? && session.try(:key)` -> ` return false if current_user.nil? && session.try(:key).nil?`

Fixes can edit function logic

---

app/helpers/application_helper.rb

Fixes Editing stuff when wrong user

---

config/initializers/devise.rb

change email for forgot password

---

app/views/data_sets/manualEntry.html.erb

For #2404.
Easy fix, just added to the time string formatter in manualEntry.html.erb.

Default dataset name now includes seconds.

---

app/assets/javascripts/templates/visualizations/controls/clipping.hbs
app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb
app/assets/stylesheets/visualizations.css.scss

For #2412.
A few small additions to disable this feature.
Let me know if you don't like the styling; I can change it real easily.

Filtering button now disabled when on Timeline with period mode turned on

---

app/assets/javascripts/visualizations/visualizations.js.coffee

Pull request #2423 causes no fields to be selected in certain circumstances. This fix resolves that issue.

Quick fix for field selection issue

---

app/assets/javascripts/visualizations/visualizations.js.coffee

If statement reordered for efficiency

Another quick hotfix - ignore that last one

---

app/assets/javascripts/projects/show.js.coffee

For #2436.
I simply added a check for the URL containing the search option.

User should now be able to visualize searched data sets.

---

app/views/projects/edit_fields.html.erb

For #2320.
Just added a short message; nothing fancy.

Proper Unauthorized message when accessing Edit Fields for someone else's project

---

app/assets/javascripts/projects/show.js.coffee
app/views/projects/show.html.erb

Issue #2433 
Fixing issue with mine button 
Changed where the ".mine" extension was added (which is how the button found which checkboxes to click) - was previously being attached to an object which was undefined

Mine button fix on data sets page

---

app/views/projects/_form.html.erb

Moved contrib key options to top of edit page and changed the description

---

app/assets/javascripts/visualizations/highvis/bar.coffee

For #2449.
One line fix, shouldn't really break anything.

Changed the default analysis type on Bar to "total"

---

app/assets/javascripts/templates/visualizations/controls/clipping.hbs
app/assets/javascripts/templates/visualizations/controls/scatter-tools.hbs
app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb
app/assets/javascripts/visualizations/highvis/highmodifiers.coffee
app/assets/javascripts/visualizations/highvis/map.coffee
app/assets/javascripts/visualizations/highvis/scatter.coffee
app/assets/javascripts/visualizations/highvis/table.coffee
app/assets/javascripts/visualizations/visualizations.js.coffee
app/assets/stylesheets/visualizations.css.scss
app/views/visualizations/_vis.html.erb

For #2452.
You can also disable points by clicking on points on the map and rows on the table.
This update removes the part of the code that would change the data point IDs when grouping options were changed. We will discuss how best to proceed in that department.

"Disable Selected Point" now disables the point in all vises.

---

app/assets/javascripts/templates/visualizations/controls/clipping.hbs
app/assets/javascripts/templates/visualizations/controls/period.hbs
app/assets/javascripts/templates/visualizations/controls/scatter-tools.hbs
app/assets/javascripts/visualizations/highvis/bar.coffee
app/assets/javascripts/visualizations/highvis/histogram.coffee
app/assets/javascripts/visualizations/highvis/map.coffee
app/assets/javascripts/visualizations/highvis/photos.coffee
app/assets/javascripts/visualizations/highvis/pie.coffee
app/assets/javascripts/visualizations/highvis/scatter.coffee
app/assets/javascripts/visualizations/highvis/summary.coffee
app/assets/javascripts/visualizations/highvis/table.coffee
app/assets/stylesheets/visualizations.css.scss

For #2450.
Bootstrap includes some very nice support for tooltips, so that's what I used. Let met know if any other controls should get tooltips; I've only added it to the most obscure controls so far.

"Help" Tooltips for vis controls

---

app/assets/javascripts/templates/visualizations/controls/clipping.hbs

To go along with all the other tooltips added in #2450.

Added tooltip for Disable Points controls

---

app/assets/stylesheets/projects.css.scss
app/views/projects/index.html.erb
test/integration/clone_project_test.rb
test/integration/contrib_key_with_data_set_test.rb
test/integration/delete_then_feature_mo_test.rb
test/integration/make_project_test.rb
test/integration/summernote_mo_test.rb
test/integration/update_fields_test.rb
test/integration/user_interactions_test.rb

For #2309.
Credit goes to @bdonald25. I just made the button bigger and fixed the tests.

Projects index page now has floating "Add Project" button in bottom right

---

app/assets/javascripts/visualizations/highvis/bar.coffee

For #2261.
Null values were easy to handle, but then I noticed a different bug where if the bar furthest to the left didn't get an error bar (thisError = {} when barData.length == 1), then it would prevent the chart bounds from resizing to fit the new error bars. This pull request fixes both of those bugs by always giving a bar an error bar.

Null values for error bars handled correctly

---

app/views/home/contact.html.erb

Changed mailto link to correct address on About the Team page.

Corrected my email address :-)

---

test/functional/home_controller_test.rb
test/functional/news_controller_test.rb
test/functional/projects_controller_test.rb
test/functional/tutorials_controller_test.rb
test/functional/users_controller_test.rb
test/functional/visualizations_controller_test.rb

Will uncomment them once the validator gets fixed on their end.

Commented out the html5 validation tests

---

app/assets/stylesheets/visualizations.css.scss

**For Issue #2489** 
Line was not functional to begin with.
Simply removed line since it was not operational

Removed line with typo (visualizations.css.scss 407)

---

app/assets/stylesheets/visualizations.css.scss
app/views/projects/clone.html.erb

**For Issue #2488** 
**See attached images:**
_Behavior before:_
_Behavior after:_

Cloning project page text will now word wrap

---

app/controllers/users_controller.rb
app/models/data_set.rb
app/models/project.rb
app/models/visualization.rb
app/views/users/index.html.erb
db/migrate/20160922171344_add_counters_to_users.rb
db/schema.rb

For #2498.
I added controls to filter users by date created and to show only users with contributions. The number of users in the current filter is shown at the top.
In order to efficiently count how many projects, data sets, and visualizations someone has, I needed to implement [counter caches](http://guides.rubyonrails.org/association_basics.html), which requires a migration.

Update user index page

---

app/assets/stylesheets/projects.css.scss

Fixed fab button on mobile

---

app/assets/stylesheets/application.css.scss
app/controllers/registrations_controller.rb
app/views/devise/registrations/new.html.erb
config/routes.rb

For #2528.
Devise doesn't handle reCAPTCHA by default, so I had to extend the the Devise Registrations controller to check for the reCAPTCHA.

reCAPTCHA verification has returned

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/sessions.css.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
config/locales/devise.en.yml
test/integration/bug_report_test.rb

For #2510.
Also removed the message about the password resets.

Moved the Google Sign In button to the top

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/bootstrap_custom.css.scss
app/views/projects/show.html.erb

For #2488, #2519, #2520, #2521.
More unified approach to fixing text overflow.

Fixed several instances of text overflow

---

app/assets/javascripts/visualizations/highvis/highmodifiers.coffee
app/assets/javascripts/visualizations/highvis/summary.coffee

For #2540.
Added a new function to highmodifiers.coffee that calculates the Standard Deviation.

Added Standard Deviation to Summary

---

app/assets/javascripts/visualizations/highvis/bar.coffee

Fixed histogram density feature

---

lib/gravatar.rb

Use https for gravatar

---

app/views/devise/registrations/edit.html.erb

For #2543.
This was never working. We didn't even have any tests for it. Word of God says users don't need to be able to delete their own accounts anyway.

Removed the ability to delete your own account

---

app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb

Only displays groups in legend or chart if they have any data.

---

app/assets/javascripts/visualizations/highvis/map.coffee

Increase heatmap radius default minimum to 20px

---

app/assets/javascripts/users/show.js.coffee
app/models/user.rb
app/views/shared/_edit_info.html.erb

For issue #2537 
Fixed persistent username edit error so that the error disappears when the username is successfully changed.

Fixed persistent username edit error

---

Gemfile
Gemfile.lock
app/controllers/visualizations_controller.rb

Change vis tab through URL

---

app/assets/javascripts/visualizations/highvis/histogram.coffee

Bin size slider matches current setting

---

app/assets/stylesheets/users.css.scss
app/controllers/users_controller.rb
app/views/users/show.html.erb

For #2576.
Button placed at the top of the user page. Works the same as the FAB on the project index page.
This should make Tyler very happy.

Added New Project button to user page

---

app/views/layouts/_footer.html.erb

For #2593.
New link shows all apps made by us.

Updated link to Google Play

---

app/controllers/visualizations_controller.rb

Consolidated some lines in visualizations_controller#displayVis

Optimized fetching of data sets

---

.gitignore
app/assets/javascripts/projects/index.js.coffee
app/assets/javascripts/projects/project_tags.js.coffee
app/assets/stylesheets/projects.css.scss
app/controllers/application_controller.rb
app/controllers/projects_controller.rb
app/models/project.rb
app/models/tag.rb
app/models/tagging.rb
app/views/projects/_form.html.erb
app/views/projects/index.html.erb
app/views/projects/show.html.erb
app/views/shared/_project_box.html.erb
config/routes.rb
db/migrate/20170128155015_create_tags.rb
db/migrate/20170128155421_create_taggings.rb
db/schema.rb
test/fixtures/taggings.yml
test/fixtures/tags.yml
test/functional/projects_controller_test.rb
test/models/tag_test.rb
test/models/tagging_test.rb
test/unit/project_test.rb
test/unit/tag_test.rb
test/unit/tagging_test.rb

add support for project tagging

---

.gitignore
app/controllers/visualizations_controller.rb
app/models/media_object.rb
app/models/news.rb
app/models/project.rb
app/models/tutorial.rb
app/models/visualization.rb

Media objects performance

---

app/controllers/data_sets_controller.rb
lib/file_uploader.rb

#2600.
Uploads are limited to 10MB.

Data upload limit

---

app/controllers/projects_controller.rb

Upload limit on templated files

---

app/controllers/projects_controller.rb

Still need to add error message when a duplicate tag is submitted

Duplicate tags can no longer be saved.

---

config/environments/production.rb

Email links don't use HTTPS for dev

---

app/views/shared/_privacy_policy.html.erb

Update privacypolicies.com link

---

app/helpers/application_helper.rb
app/views/data_sets/dataFileUpload.html.erb

As Tyler requested, made a button green for #2620.
Also set a title for this page as the default was "Data_sets"

Make button green and fix page title

---

app/views/home/index.html.erb

No longer opens Visualizations in new tab

---

app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb

For #2649 
Uses plain HTML with embedded CSS and static image, as email supports only a subset of CSS, and no separate stylesheets.

Styled emails

---

app/assets/javascripts/visualizations/highvis/scatter.coffee
app/assets/stylesheets/visualizations.css.scss

For #2612 
Also no longer need to make icons even smaller on mobile : )

Scrollbar instead of wrapping!

---

Gemfile.lock
app/assets/javascripts/templates/visualizations/controls/tip.hbs
app/assets/javascripts/visualizations/highvis/bar.coffee
app/assets/javascripts/visualizations/highvis/highmodifiers.coffee
app/assets/stylesheets/visualizations.css.scss
test/fixtures/data_sets.yml
test/fixtures/fields.yml
test/fixtures/projects.yml
test/fixtures/users.yml
test/integration/control_tip_test.rb

Get grouping suggestion when default is useless

---

app/assets/javascripts/templates/visualizations/controls/save.hbs.erb
app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb

Export buttons shouldn't show up on non-highcharts

---

app/views/users/pw_send_key.html.erb
config/locales/devise.en.yml

Add spam folder warnings when sending email

---

app/views/projects/show.html.erb

Right-align dropdown

---

app/models/data_set.rb

Add missing exception handler

---

app/assets/javascripts/visualizations/highvis/filters.coffee
app/assets/javascripts/visualizations/highvis/highmodifiers.coffee

Fix timestamp filtering

---

app/assets/javascripts/visualizations/highvis/histogram.coffee

Use attr instead of val

---

app/assets/javascripts/data_sets/editTable.js.coffee
app/assets/javascripts/templates/visualizations/photo/group.hbs
app/assets/javascripts/visualizations/highvis/photos.coffee
app/assets/stylesheets/application.css.scss
app/assets/stylesheets/data_sets.css.scss
app/assets/stylesheets/visualizations.css.scss
app/views/data_sets/edit.html.erb
app/views/data_sets/manualEntry.html.erb
test/integration/clone_project_test.rb
test/integration/slickgrid_test.rb
test/integration/user_interactions_test.rb

Photos Vis works, looks nice, and photo upload is easier

---

app/controllers/media_objects_controller.rb

Easy fix: strip ( ) from file names on upload

---

app/views/projects/_tag_editor.html.erb

Raise tag limit to 16

---

app/controllers/data_sets_controller.rb

Fix google slides upload issue

---

app/assets/javascripts/visualizations/highvis/bar.coffee
app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb
app/assets/javascripts/visualizations/highvis/box.coffee
app/assets/javascripts/visualizations/highvis/histogram.coffee
app/assets/javascripts/visualizations/highvis/map.coffee
app/assets/javascripts/visualizations/highvis/photos.coffee
app/assets/javascripts/visualizations/highvis/pie.coffee
app/assets/javascripts/visualizations/highvis/scatter.coffee
app/assets/javascripts/visualizations/highvis/summary.coffee
app/assets/javascripts/visualizations/highvis/table.coffee

Reverts isenseDev/rSENSE#2680
Revert for 2 reasons:
- Broke Photos vis
- Redirected to 404 page

Revert "Detect when vis fails to render"

---

.ebextensions/deploy.config
lib/file_uploader.rb

Installs libreoffice on the server

---

app/assets/javascripts/visualizations/highvis/bar.coffee
app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb

Add Analysis Type "Mean with 2 SEM"

---

app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb
app/assets/javascripts/visualizations/visualizations.js.coffee

Hamburger menu hidden by default on mobile

---

app/assets/javascripts/templates/visualizations/photo/pic.hbs
app/assets/javascripts/visualizations/highvis/bar.coffee
app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb
app/assets/javascripts/visualizations/highvis/box.coffee
app/assets/javascripts/visualizations/highvis/histogram.coffee
app/assets/javascripts/visualizations/highvis/map.coffee
app/assets/javascripts/visualizations/highvis/photos.coffee
app/assets/javascripts/visualizations/highvis/pie.coffee
app/assets/javascripts/visualizations/highvis/summary.coffee
app/assets/javascripts/visualizations/highvis/table.coffee

This version is very similar to [last time](https://github.com/isenseDev/rSENSE/pull/2680), but now:
- Redirects home to make things simpler and foolproof
- Does not break photos vis as a side-effect

Detect when vis fails to render 2.0

---

app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb

Revert "Hamburger menu hidden by default on mobile"

---

README.rdoc
circle.yml

Hi all, I don't know if any of you know me at this point but I worked in the ECG lab under Fred between 2010 and 2014! I now work for Black Duck Software where my main project recently has been a free tool for doing security scans on open source GitHub projects called [CoPilot](https://copilot.blackducksoftware.com).
We just added support for Ruby in our release yesterday, and I was talking with @jaypoulz who suggested trying the tool on iSENSE, so here we are!
I integrated the tool into your Circle CI build. It turns there's some issues, you have a high security risk: https://copilot.blackducksoftware.com/github/repos/isenseDev/rSENSE/branches/add-security-scan
The scan will re-run whenever a Circle build runs (in a few weeks we're adding support for building pull requests which will …

Add component security scan

---

app/assets/stylesheets/application.css.scss

Fix appvis box UI issue #2745

---

app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb
app/assets/stylesheets/application.css.scss

[JS-2712] Fix spelling of 'mininim'

---

app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb
app/assets/stylesheets/application.css.scss

Revert "[JS-2712] Fix spelling of 'mininim'"

---

app/assets/stylesheets/application.css.scss

He accidentally undid a previous PR, so I made a new branch incorporating the intended changes.  My bad for allowing it through review...

Fix issue with Joel's PR I shouldn't have approved

---

app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb

Make Group by Number Fields work on Pie again

---

app/assets/javascripts/projects/show.js.coffee
app/assets/stylesheets/projects.css.scss
app/controllers/projects_controller.rb
app/models/user.rb
app/views/projects/show.html.erb

Also change minimum username length from 4 to 1 at the point of registration

JS-2757a: Add Pagination and Drop Down per_page toggle

---

app/views/visualizations/_vis.html.erb

Get Latest Data --> Get All Data

[JS-2772] Change wording of get all data sets button on visualization page

---

app/assets/stylesheets/home.css.scss
app/views/home/contact.html.erb

[JS-2748] Fix display bug on contact page at certain widths

---

app/assets/javascripts/visualizations/highvis/bar.coffee
app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb
app/assets/javascripts/visualizations/highvis/box.coffee
app/assets/javascripts/visualizations/highvis/histogram.coffee
app/assets/javascripts/visualizations/highvis/map.coffee
app/assets/javascripts/visualizations/highvis/photos.coffee
app/assets/javascripts/visualizations/highvis/pie.coffee
app/assets/javascripts/visualizations/highvis/summary.coffee
app/assets/javascripts/visualizations/highvis/table.coffee

Prompt to view tutorial and redirect to tutorial page

---

app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb
app/assets/javascripts/visualizations/highvis/highmodifiers.coffee
app/assets/javascripts/visualizations/highvis/scatter.coffee

For #2560 
This pull request is all the code from the [previous pull request](https://github.com/isenseDev/rSENSE/pull/2765), but removing some side-effects on timeline period.  Also addresses an issue where periods weren't overlapping properly and scatter X-Values would be converted to timestamps!

Make group by number fields work again

---

app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb

How'd that get through code review? :thinking:

Remove debugger statement

---

app/assets/javascripts/visualizations/highvis/table.coffee
app/assets/stylesheets/visualizations.css.scss

For #2780.  Also makes 'X' buttons in text fields only appear when there's actually something to clear.

Makes table filters look clickable

---

app/views/home/contact.html.erb

Forgot to add http so it was trying to find my site in the iSENSE project.

added http to CB personal website

---

app/assets/javascripts/projects/show.js.coffee
test/integration/delete_selected_datasets_test.rb

 Reload page when last dataset is removed

---

app/assets/javascripts/visualizations/highvis/histogram.coffee

Histogram boxes display correct values

---

.ebextensions/deploy.config

For #2710 
Tested on Dev server

Use symlink to get libreoffice command

---

app/assets/javascripts/visualizations/highvis/highmodifiers.coffee

 Re-enable == and != ops

---

.ebextensions/deploy.config

Will cut down wait times for deploys.  We don't need any fancy new libreoffice version

 Only install libreoffice if it doesnt exist already

---

.circleci/config.yml
Gemfile.lock

Trying to fix circle ci test errors associated with capybara.

[SNSE-7] Fixed CI errors with Capybara

---

.gitignore
test/unit/news_test.rb
test/unit/tutorial_test.rb
test/unit/user_test.rb

[SNSE-15]
[SNSE-15]: https://isense-project.atlassian.net/browse/SNSE-15

[SNSE-15] fixed deprecation warning relating to nil

---

.gitignore
app/controllers/projects_controller.rb
app/controllers/visualizations_controller.rb

This change should enforce that user inputs match predefined allowed values.

Fixed an issue with input sanitization

---

Gemfile.lock
app/assets/javascripts/visualizations/highvis/table.coffee

Changed eq's value from "==" to "=", added operands in the filterToolbar parameter, and copy and pasted the operands array between navGrid params and filterToolbar params.

Modified table.cofee to display = instead of ==

---

Gemfile.lock
app/assets/javascripts/visualizations/highvis/table.coffee

This is a pull request for the colorpicker API fix, which should allow a user to select a color

colorpickerfix

---

app/controllers/visualizations_controller.rb

This bug was related to thumbnails not getting saved while creating visualization. After changing the code it started working.

2927-viz saving failing on visulization
