engaging-computing/rSENSE

test/integration/upload_media_test.rb
In my most recent patch, I thought I fixed the issue causing upload media test to intermittently break.  Turns out this is simply a synchronization error.  The test now assures clicking each media object's edit button brings the user to /media_objects/:id (media_objects#show).
Should address @bdonald25 's issue where the Upload Media Test broke randomly.
=> Upload Media Test is actually fixed now!

app/helpers/application_helper.rb
Addresses #1912 
Admin used to have the `Delete` button show up despite not being able to actually delete a project with data sets.  Fixed now.
=> Delete button no longer show up for admin if data sets are in project

app/controllers/projects_controller.rb, app/models/project.rb, app/views/projects/clone.html.erb
Addresses #1668 
There were a few issues:
- New, cloned media objects weren't being pushed back into the new project's own media objects array
- The project was being saved before media was even cloned
- Whoever wrote the piece that `gsub!` the project's content was editing a local variable, not the new project's content property :stuck_out_tongue: 
Also refactored a couple project files.
=> Fixed project cloning having a description that links back to old project's media

app/helpers/application_helper.rb
Previously, the user page worked as intended for non-admins: clicking the "Liked Proj" tab and "My Projects" tab worked, and you were free to roam amongst them.  However, we were getting a 500 error crash for admins.
Turns out it's because admins have the ability to hide anyone's project, and if that project no longer has an owner, you'll crash when checking that owner's ID in the `can_hide?` method of `application_helper.rb`.
Addresses #1795.
:large_blue_circle: :palm_tree: :sunrise:
=> Fixed admin liked proj page

app/controllers/visualizations_controller.rb
this makes it possible to embed URLs like: 
/projects/[projectNum]/data_sets/[dataSetIdList]?embed=true
Being able to embed those URLs is useful so I can make a tool which filters lists of data_sets for the user and shows the default visualization of this filtered set of data_sets.
=> allow data_set visualizations to be embedded too

app/assets/stylesheets/api.css.scss
Replaced text cursor with a pointer to indicate you can expand api docs by clicking on get or post.
#1995
=> pointer when hovering above get or post in api docs

app/assets/javascripts/visualizations/highvis/table.coffee
Addresses #1980 
The problems were:
- the code was checking the length of all fields versus selected fields instead of very simply checking if the "#Check All" box was selected or not, leading to the error described in the issue
- yFields was improperly being modified in the click event of the "#Check All" box - switched it to a temp variable called selFields
Additionally:
- Changed some "($ " to "$("
- Changed the name of the box to "#Check All" instead of "#Select All" to be consistent with the groups check-all box
=> Fixed check-all bug in table for visible fields

app/assets/javascripts/visualizations/highvis/map.coffee, app/controllers/projects_controller.rb, app/views/projects/_form.html.erb, app/views/visualizations/displayVis.html.erb, db/migrate/20150225125927_add_kml_to_project.rb, db/schema.rb
A URL to a KMLl file can be given to a project in the project/edit page. 
The map will then show that layer independent of any data that the user uploads.
There is not a test written for this yet, could @JKinsman or @bdonald25 please figure out a functional test for this, simple as setting the value and making sure its set. 
A sample kml file can be found at http://edna.usgs.gov/watersheds/sheds/USWatersheds/USWatersheds.kml
=> Adding basic kml layer support

app/views/projects/show.html.erb
Addresses #1985
1. You should not be able to enter a key when you're logged in.
2. The option to enter a contributor key for non logged in users should only appear when a project has fields.
=> Contributor key only displays when appropriate

app/assets/javascripts/projects/show.js.coffee, app/assets/javascripts/shared/confirm_nav.js.coffee, test/fixtures/projects.yml, test/integration/edit_proj_desc_test.rb
Addresses #1828 
Even added some tests to cover editing project descriptions and ensuring the pop-up I implemented here works as intended (that is, asking for navigation confirmation if the project description was modified, not saved/canceled, and the user tried leaving the page).
=> Navigation confirmation for leaving project page without saving description

app/controllers/media_objects_controller.rb, test/functional/media_objects_controller_test.rb
Addresses #2025 
Rather than redirecting to the media_object's parent (always the project page), we now redirect back to wherever we were before.  Hooray. :camel:
=> Better redirect on media delete

app/assets/javascripts/visualizations/highvis/bar.coffee, app/assets/javascripts/visualizations/highvis/histogram.coffee, app/assets/javascripts/visualizations/highvis/map.coffee, app/assets/javascripts/visualizations/highvis/pie.coffee, app/assets/javascripts/visualizations/highvis/scatter.coffee, app/assets/javascripts/visualizations/highvis/timeline.coffee, app/assets/javascripts/visualizations/highvis/visUtils.coffee
Addresses issue #2046 .  Units (when they exist) are now displayed next to every measurement on every visualization tooltip.  @jaypoulz sorry for adding more html strings to the js!  Oops! :stuck_out_tongue: :smile:
=> Added unit information to tooltips

test/functional/users_controller_test.rb, test/helpers/data_sets_helper_test.rb, test/integration/api_v1_test.rb, test/integration/rename_viz_test.rb
Some of the test names needed adjustments.
- removed commas/apostrophes/dashes
- test names < 70 chars
- test names belong in single quotes
- misspellings fixed
Addresses no issue, just a quick formatting change.
=> Fixed some bad test names

app/models/project.rb, test/integration/clone_project_test.rb
1) Quick fix, @stowellm accidentally broke this on January 14th while trying to fix another bug. 
```ruby 
new_project.id
```
is null until it exists. Cloning in general is a bit wonky and needs a rewrite at some point, but it is not high priority. 
2) Added a test to make sure this doesn't happen again.
#2071
=> Fields should be copied when cloning a project.

app/views/home/api_v1.html.erb
This removes any spaces from the version number. The version on travis is "Development Version" which causes it to fail HTML validation because it has a space.
=> remove spaces from version number on api page

app/views/layouts/application.html.erb
"iSENSE" logo no longer becomes "iS" when the browser is resized.
=> Logo is no longer shortened on resize

app/assets/stylesheets/application.css.scss, app/assets/stylesheets/projects.css.scss
Project tiles may show up in various places. So the CSS should not be restricted to the projects controller.
@stowellm  this should address your concerns for #2095
=> Moving CSS rule from Projects to Application

app/controllers/fields_controller.rb, app/helpers/data_sets_helper.rb, app/models/field.rb, db/migrate/20150511165600_fix_bad_restrictions.rb, db/schema.rb, lib/file_uploader.rb, test/fixtures/projects.yml, test/helpers/data_sets_helper_test.rb
Addresses #2024.
Field restrictions are now constrained to being just an array of restrictions.  Previously, a lack of restrictions could be represented as an empty string, an empty array, or nil.
This was done by having the fields model actually validate restrictions.  I also had to fix some tests, and I removed some code from FileUploader that would reject any text entered in a field that had no restrictions because the entered text wasn't in the empty array of restrictions.
I also cleaned up how validation was done.  I am also no longer returning just one error if the user fails create a field, but instead all of them.  This useful in regards to the API and stuff.
=> Fixes field restrictions

app/assets/javascripts/visualizations/highvis/histogram.coffee
Addresses #2127.
Very easy fix.  Now histogram shows the actual recorded value over the value that results from binning it.  Only does things on vises that actually show individual records.
=> Histogram now shows real numbers instead of binned numbers

app/assets/javascripts/application.js, app/assets/javascripts/visualizations/highvis/bar.coffee, app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb, app/assets/javascripts/visualizations/highvis/pie.coffee, db/migrate/20150519161334_add_mean_error_bars.rb, test/fixtures/tutorials.yml, test/fixtures/visualizations.yml
Addresses #1896, #2158.
Fixes the migration to test a little more rigorously for what data is actually present in saved and default vises.  Turns out it was less consistent than I thought it was.
Also fixes standard deviation on logarithmic y-axis.  According to [this article](http://www.graphpad.com/faq/file/1487logaxes.pdf), showing standard deviation error bars on a log y axis is considered an "abuse" and makes literally no sense, so I made my fix reflect that.  Only the top part of error bars for non-negative means are shown.
=> Standard deviation on bar chart again

app/assets/javascripts/templates/visualizations/controls/histogram-tools.hbs, app/assets/stylesheets/application.css.scss
#2169
The icons on the project boxes no longer overflow.
=> Fixes overflow on the project boxes.

app/assets/javascripts/visualizations/highvis/table.coffee
Previously the number of columns that a table had by default was 8 regardless of screen size. Now it is based upon the screen's width.
Fixes #2156
=> Number of columns on table is now based on screen size

app/controllers/projects_controller.rb
Addresses #2180.
When you delete a project that has been cloned from, it tells all of the clones that you deleted their parent.  This prevents the website from breaking when a user tries to view a project that comes from a cloned project.  The break happens because it called `Project.find(id)` although `id` isn't in the database.
I didn't bother writing a migration because this hasn't happened on live.  The only way that this can happen is if the cloned project doesn't have data, which doesn't really make much sense to do in practice.
=> Tells cloned projects that their parent is dead when you kill them

app/assets/javascripts/shared/media_objects_view.js.coffee, app/models/project.rb, test/unit/project_test.rb
Addresses #1262, #2196
The AJAX can be broken down as follows:
* **shared/media_objects_view:** removed useless block of code for deleting pictures, added validation for featuring media objects
* **visualizations/highvis/savedVis:** not touching this, as it's important and recent so it's OK
* **data_sets/editTable:** needed because data needs to persist in case you did something wrong
* **users/show:** used for efficiently sorting and filtering user contributions and hiding/unhiding stuff
* **projects/show:** used for liking,  and deleting data sets and saved visualizations
So, overall, I made a change.
Also, I had to fix some stuff regarding media objects.  That was fixed, and now we actually validate featured media objects.
=> Purges useless AJAX and can no longer set invalid media objects as featured

Gemfile, Gemfile.lock, app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb, db/schema.rb
Addresses #2004.
Companion pull request for https://github.com/isenseDev/better-colorpicker/pull/1.  Don't do anything with this until that is merged.
This gets rid of the old colorpicker.  It was a good first try, but it had a couple of problems.  Primarily, it would created one instance of itself in the DOM per group.  This is OK on most projects, but was still bad practice.  It also allowed more than one color picker to exist on screen at a time.
This should probably be tested locally before being merged.
=> Fixing duplicate colorpickers

app/assets/javascripts/visualizations/highvis/photos.coffee
Addresses an issue raised in a pull request.
Turns out group names are lowercased versions of the data set name.  That's weird.  I also added a nullity check just in case.
=> Fixed problem with photo grouping

app/assets/javascripts/visualizations/highvis/timeline.coffee
#2203 Fixes detailed tool tips.
My commit says scatter but it is really for timeline.
=> fix detailed tool tips for timeline

app/views/shared/_vis_box.html.erb
Wrong way to check if a attribute is set.
=> fixing viz index bug.

app/assets/javascripts/home.js.coffee, app/assets/stylesheets/application.css.scss, app/views/layouts/application.html.erb, app/views/projects/show.html.erb, test/integration/api_v1_test.rb, test/integration/base_integration_test.rb, test/integration/bug_report_test.rb, test/integration/clone_project_test.rb, test/integration/contrib_key_with_data_set_test.rb, test/integration/delete_then_feature_mo_test.rb, test/integration/edit_proj_desc_test.rb, test/integration/embedded_vis_test.rb, test/integration/make_project_test.rb, test/integration/post_news_test.rb, test/integration/register_test.rb, test/integration/rename_vis_test.rb, test/integration/search_data_sets_test.rb, test/integration/show_user_test.rb, test/integration/slickgrid_test.rb, test/integration/small_page_test.rb, test/integration/summernote_mo_test.rb, test/integration/tutorials_test.rb, test/integration/update_fields_test.rb, test/integration/upload_data_test.rb, test/integration/upload_media_test.rb, test/integration/upload_zip_test.rb, test/integration/user_sorting_test.rb
* adds some code that makes forms visible during tests (because Capybara doesn't like that)
* I know this is bad but it's better than failing tests and that's literally the only other option
* adds a base integration test that sets the default wait time for every test, so the default is an actual default and not affected by the order of test execution
* deleted all the calls to `page.execute_script` with the above changes and everything passes now
=> Fixes the integrations

app/controllers/application_controller.rb, test/fixtures/data_sets.yml
#2251
It was previously comparing the label of the key that was used to create the data set and the key that the user was passing as a parameter.
=> fix appending and editing for contribution keys through api

test/unit/news_test.rb
Fixes four tests that are failing. 
The message they get is something along the lines of "expected 'over 239 years' but got 'almost 240 years'"
=> fixes tests

Gemfile, Gemfile.lock, lib/file_uploader.rb, test/integration/slickgrid_test.rb
No associated bug report.
Test for slickgrid are failing for an issue seemingly related to daylight savings time.  Some (not all) of the times entered during testing were converted to GMT incorrectly.  This behavior was not exhibited during normal execution.  I managed to narrow it down to an issue in the browser the integration tests were run on, but I couldn't figure out the exact problem so I changed the test to use a fixed date that for sure will not fail.
This updates better-datetimepicker to a version that changes the event for selected months, years and times.  This should be tested next release.
*helicopter noises*
=> Slickgrid tests are now invariant to abstract notions of "local time"

app/assets/javascripts/visualizations/highvis/scatter.coffee
#2276 
Basically, one of the objects in the scatterplot vis was undefined, so when the script tried to access it, it threw an Uncaught TypeError, so it halted the rendering of the page.
=> Fixed issue ps2276 - project 891 breaks vis rendering

app/assets/javascripts/visualizations/highvis/highmodifiers.coffee
=> Groups no longer lose capitalization in the Group By function

test/integration/number_of_data_sets_test.rb
No associated bug.
Last release had a test that clicked a check box. Material design was merged at the same time and it broke the way the test found the check boxes. This fixes the test so it finds the check boxes correctly.
=> Fixes a test that broke from material design

app/assets/javascripts/projects/show.js.coffee, app/assets/javascripts/templates/visualizations/controls/map-tools.hbs, app/assets/javascripts/visualizations/visualizations.js.coffee, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/projects.css.scss, app/assets/stylesheets/visualizations.css.scss, app/controllers/projects_controller.rb, app/controllers/visualizations_controller.rb, app/views/projects/_form.html.erb, app/views/projects/edit.html.erb, app/views/projects/index.html.erb, app/views/projects/show.html.erb, app/views/shared/_project_box.html.erb, app/views/shared/_vis_box.html.erb, app/views/visualizations/_vis.html.erb
#2305 Material Continued .. Fixed edit project page and added a material slide for the heat map.
#2321 Check boxes were not letting you select all by key. This was because material design requires a function be called on a check box's label to check them instead of manually changing the css class of the check box itself. I updated all cases of checking boxes from the js but I missed this one case.
#2140 Updated the vis tools to work on mobile. On small screens it opens over the vis instead of pushing it to the side. The tools are also skinnier on mobile so they do not take up the whole screen.
#2309 I updated the cards on the index pages to look nicer. I also partially fixed this bug. (I did not address the extra box when logged in) I will fix this last issue if we do not go with the fab …
=> UI changes (Material Design and mobile vis tools)

test/integration/slickgrid_test.rb, vendor/assets/javascripts/slickgrid-editors/slickgrid-decimal.coffee
#2287
Had to update the regular expression and add a call to .trim() in slickgrid-decimal.coffee.
=> Now able to trim leading and trailing whitespace when manually entering number fields

app/helpers/application_helper.rb
#2301
Removed a call to ".capitalize" on the project's title.
=> HTML Title tag now displays project title with correct case.

app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb, app/assets/javascripts/visualizations/highvis/histogram.coffee, app/assets/javascripts/visualizations/highvis/map.coffee
#2326 Fixes the check boxes for map. 
I also fixed the slider on map so that it is always Material Design. It was previously losing its styling when switching to another vis and switching back.
=> fixes map checkbox

app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb
This fixes issue #2291. The root of the problem is an [error in highcharts](https://github.com/highcharts/highcharts/issues/1093) that has gone unfixed for years. The workaround I made was to manually resize the page after the print dialog closes.
=> Canceling print no longer breaks vis

app/assets/javascripts/visualizations/highvis/filters.coffee, test/integration/filter_timestamp_label_test.rb
Fixes issue #2365. In filters.coffee, the formatter was set but never used. I simply changed it so that the formatter variable was actually used. Also added a test to make sure it stays fixed.
=> Filter labels for time stamps are now formatted correctly.

app/assets/javascripts/users/show.js.coffee, app/controllers/data_sets_controller.rb, app/controllers/projects_controller.rb, app/controllers/visualizations_controller.rb
This fixes issue #2239. The cause was the line of code `e = JSON.parse xhr.responseText`. The problem was that xhr.responeText returns some sort of stack trace, which is not JSON. So when JSON.parse tries to parse it, it throws a syntax error.
I have now fixed the original database calls, which were throwing uncaught RecordNotFound exceptions. They are now handled and pass an appropriate error message to the user page.
=> User page now shows correct error message when trying to delete a missing item.

app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb
This fixes issue #2290. The fix was to simply resize the vis to 700 if it is larger than 700 (700 being the approximate width of the printed page).
=> Large visualizations are resized before printing so they are not cut off

app/assets/stylesheets/visualizations.css.scss
#2358
The bug here was that when you selected a row of the table, a border was created around the row in a really ugly light yellow color.  The border was around all of the row/column lines in that row except for the top line.  I overrode the bad table selection highlighting by overriding the problem class with a class that adds an even, dark blue border just around the row itself.
Since there weren't any specific requests for what the correct table select should look like, and I couldn't find any similar outline selection anywhere else on the website to match it with, I just kind of used my judgement as to what looked good.  It's definitely better than the yellow, but if you need me to change the outline color, thickness, background-color, etc just let me know and I can update that too.
=> fixed bug #2358 bad table select highlight color

app/models/data_set.rb, config/environments/production.rb
The Formula Fields code is broken - it currently fails when a user tries to upload Timestamp data from an API or a CSV. For whatever reason, the portion of code that breaks runs whether or not the user actually has any formula fields set up.
The temporary fix is to abort the faulty function if there are no formula fields present. This will allow us to continue using APIs for now, but a more robust fix is needed ASAP.
=> Temporary fix for uploading data from CSV or API

app/assets/javascripts/visualizations/highvis/savedVis.coffee
Newer versions of ImageMagick had issues with the way that Highcharts exports SVGs of charts. Specifically, it didn't like that the first few fonts in the style attribute had single quotes around them:
`style="font-family:'lucida grande', 'lucida sans unicode', arial, helvetica, sans-serif;font-size:12px;"`
To fix it, I just removed those two fonts from the list:
`style="font-family:arial, helvetica, sans-serif;font-size:12px;"`
This doesn't change the way the site works, because our site just uses Arial anyway.
=> Newer versions of ImageMagick now work with our development environment.

.gitignore, app/assets/javascripts/visualizations/highvis/bar.coffee, app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb, app/assets/javascripts/visualizations/highvis/highmodifiers.coffee, app/assets/javascripts/visualizations/highvis/histogram.coffee, app/assets/javascripts/visualizations/highvis/map.coffee, app/assets/javascripts/visualizations/highvis/pie.coffee, app/assets/javascripts/visualizations/highvis/scatter.coffee, app/assets/javascripts/visualizations/highvis/summary.coffee, app/assets/javascripts/visualizations/highvis/table.coffee, app/controllers/visualizations_controller.rb
Fixes #2388.
If a visualization has no time data, the period tool and period group-by option will both be removed. 
Fixed an error where the period feature would mess up the x-coordinates on the Scatter vis.
When grouping by Time Period: if some data points were missing timestamps, they will be put into the "No Time Data" group.
=> Period feature now correctly removed when project has no timestamps

app/assets/javascripts/templates/visualizations/controls/base-tools.hbs, app/assets/javascripts/visualizations/highvis/bar.coffee, app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb
For feature request #2399.
In order to implement this feature, basically all of bar.coffee had to be rewritten. Before, it utilized Highcharts' 'category' feature, in which bars are automatically grouped together based on a label. However, this way of doing things is completely incompatible with being able to draw points on top of the bars, as the points would just push the bars around. In addition, the bars used to be added each as their own series. That also causes the bars to be moved around in a way that cannot be tracked/controlled.
Now, bars are drawn to a specific x-coordinate, and all bars are part of a single series. This allows for the scatterplot points to be drawn at those same x-coordinates.
Using 'category' was prettier and easier, but rewriting the file had to be done to …
=> Histogram Density (show underlying points for each bar)

app/assets/javascripts/visualizations/highvis/scatter.coffee
For #2364.
All I had to do was use Highcharts' [minRange](http://api.highcharts.com/highcharts#xAxis.minRange) option to limit the minimum range to 1e-10. If we wanted to limit the zoom based instead on the range between points, that can be done mathematically. But this is good for now.
=> Fixed Scatter plot zooming crash by limiting zoom level.

app/assets/javascripts/visualizations/highvis/highmodifiers.coffee
For #2403.
A single line was deleted a while back, which caused this bug but somehow didn't break filtering completely.
=> "Filters:" No longer appears at the top of the vis every other time the vis selection changes

app/models/data_set.rb, app/models/field.rb, app/models/formula_field.rb, test/integration/user_interactions_test.rb
For #2413.
Input sanitization is done at the database level, so even data coming from APIs and CSVs gets sanitized.
All HTML tags are stripped away, which is fine because I can't think of a use case when someone would need \<brackets\> in their dataset.
=> Users can no longer inject client-side code into the website.

app/assets/javascripts/visualizations/highvis/photos.coffee
For #2416.
Simple on-line fix.
=> Group-by option changes automatically when opening Photo vis.

app/assets/javascripts/visualizations/highvis/table.coffee
For #2411.
I ended up refactoring table.coffee to fix this issue. Originally, it would put all the data for all fields into the table, then later remove the columns that were not checked off. Not only is that just bad form, it also presented a problem because the jqGrid function hideCol() would take anywhere from 80 to 120 ms to run each time it is called.
table.coffee now only puts the currently visible fields into the table, thus eliminating the need for hiding anything. This solution required a small bit of rewriting the existing code, as much of it was written based on the assumption that all of the fields were in the table.
=> Table vis no longer takes a long time to load on projects with a lot of fields.

app/assets/javascripts/visualizations/highvis/map.coffee, app/controllers/application_controller.rb
For #2421.
This was broken by the move to Devise because a single line of code was not changed with the rest. That line has been updated, and now everything works like a charm.
=> Users can once again use the API to upload media objects to data sets with contributor keys

app/assets/javascripts/visualizations/highvis/filters.coffee, app/assets/javascripts/visualizations/highvis/table.coffee
For #2410.
The source of the issue was that the data precision filter was being applied to the strings, which would return NaN. For the sake of simplicity, I just added a filter for strings that simply returns the string.
I also broke table filtering in #2418, so I fixed it here.
=> Table no longer shows [NaN] when filtering by string.

app/assets/javascripts/visualizations/highvis/map.coffee
Reverts #2134.
I received an executive order to remove the special camera marker icon on the map because it was "ugly". Points with images now look the same as all the rest. May revisit this later, along with a reworking of images.
=> Camera marker no longer appears on map vis

app/assets/javascripts/projects/show.js.coffee
For #2376.
Real simple fix to make the "Visualize" URL default to just "/data_sets/" when they are all selected.
=> Hotfix for too-long URL bug

app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb, app/assets/javascripts/visualizations/highvis/pie.coffee, app/assets/javascripts/visualizations/highvis/scatter.coffee, app/assets/javascripts/visualizations/visualizations.js.coffee
For #2405.
This is a long-standing bug, and I'm surprised it's taken this long for someone to notice it, but it is now fixed.
In the future: Try not to refer to objects solely by indices in an array, especially when those indices can change without the program knowing (which is how iSENSE has worked for the past 3 years).
=> Reordering or adding fields no longer breaks the vis

app/assets/javascripts/visualizations/highvis/bar.coffee, app/assets/javascripts/visualizations/highvis/scatter.coffee, app/assets/javascripts/visualizations/visualizations.js.coffee
For #2405.
This pull request is an extension of #2423. The default sort on bar chart now correctly changes itself when the fields were reordered, and a quick fix to scatter should stop it from resetting the defaults on existing projects.
=> A few more patches to fix the Field Reordering bug

lib/file_uploader.rb
For #2432.
Just had to add .aia to the list of valid media extensions.
=> Users can now upload App Inventor project files

config/environments/production.rb
For #2392.
We won't be able to see if this works until it's in production, but this is [how Devise says to do it](https://github.com/plataformatec/devise/wiki/How-To:-Use-SSL-(HTTPS)).
=> Changed devise reset email to use HTTPS

app/models/field.rb
For #2368.
Instead of trying to debug the bowl of spaghetti that is the vis code, I just added a validation so that the user cannot reuse the hidden fields used for grouping ('Data Point', 'Data Set Name (id)', 'Combined Data Sets', 'Number Fields', 'Contributors', and 'Time Period'). I don't really like the idea of inserting these special fields for grouping, but it's so entrenched that it's going to stay pending another rewrite.
=> Users can no longer create fields with the same name as secret group-by fields

app/controllers/projects_controller.rb
For #2319.
I'm guessing this bug exists because whoever originally wrote the code for delete_hidden_fields assumed that field.destroy would run the field_controller's destroy, which handles the error correctly, but it actually just jumps straight to the model and deletes it without checking anything.
If you do manage to press the delete button when you're not supposed to, it won't actually delete anything anymore and display an error. It also won't put those fields back onto the table, but since the user isn't supposed to be able to do that anyway, I think it's fine.
=> Fields can no longer be deleted when the project has data sets.

app/controllers/projects_controller.rb, app/views/projects/_form.html.erb
For #2443.
The button sets project.globals to nil. Hopefully this button will come in handy if we ever see another "This project breaks vis badly" issue report (#2261).
=> "Reset Defaults" button added to Edit Project page

app/assets/javascripts/templates/visualizations/controls/scatter-tools.hbs, app/assets/javascripts/visualizations/highvis/highmodifiers.coffee, app/assets/javascripts/visualizations/highvis/scatter.coffee
For #2343.
Works well for removing outliers for regressions.
Initially I wanted to have a little pop-up/tooltip under the point when you click on it, but it would look crowded in addition to the existing tooltip, and it was prohibitively complicated to get it working that way with Highcharts.
=> Users can now disable points from the scatter vis

app/assets/javascripts/projects/show.js.coffee, app/controllers/data_sets_controller.rb
There is currently an issue with removing multiple rows from the JQuery data set table on the project page. For now, The page will just refresh after the delete occurs.
=> Delete Selected Data Sets refreshes Project page

app/assets/javascripts/visualizations/highvis/highmodifiers.coffee, app/assets/javascripts/visualizations/highvis/map.coffee, app/assets/javascripts/visualizations/highvis/table.coffee, app/assets/javascripts/visualizations/highvis/visUtils.coffee
For #2265. For real this time.
Group titles should no longer show as all-lowercase, all the time anymore. This has the side effect of making different capitalizations of the same word (e.g. USA vs usa) be put into different groups. @fgmart  decided that this was the behavior we should go with.
=> Group titles no longer lose capitalization.

app/assets/javascripts/data_sets/editTable.js.coffee
For #2323.
For whatever reason, clicking outside the table would do weird stuff with activeCell on slickgrid. Slickgrid knew that you were clicking a cell (printing out the cell from @grid.onClick would show the correct cell), but it would just not set it active for editing. This fix simply sets the activeCell attribute if the clicked cell is the same as the previous activeCell.
=> No longer need to double click a cell to bring focus back on manualEntry table

app/assets/javascripts/visualizations/highvis/scatter.coffee
For #2322.
The fix for this ended up being really weird. I stared at scatter.coffee for hours, making random little changes, and got nowhere. On a whim, I added the option "shared: true" to the tooltip, and the issue disappeared. We will watch it to make sure this doesn't break anything else.
=> Scatter tooltip no longer uses data from bottom-most point when points overlap

app/controllers/projects_controller.rb, app/models/data_set.rb, app/models/project.rb, lib/file_uploader.rb, test/CSVs/commas.csv, test/fixtures/data_sets.yml, test/fixtures/projects.yml, test/integration/upload_data_test.rb, test/integration/user_interactions_test.rb
For #2277.
CSVs will automatically escape commas when the item is surrounded by  double quotes, so we now export CSVs with commas escaped where they occur. There is also a step in the upload process where we turn all uploaded docs into a CSV temporarily, so the commas needed to be escaped there as well.
Decided to throw in a few more tests while I was at it.
=> Commas in field names and data points are now properly escaped, both for importing and exporting.

app/controllers/visualizations_controller.rb, test/functional/visualizations_controller_test.rb
For #2474.
The vis page used to break when it was given a project/data set id that did not exist, or if it was given a data set id that did not belong to the selected project.
=> Vis page correctly redirects to 404.

lib/assets/javascripts/dateParse.coffee
For #2284.
The date parser originally just switched the month, day, and year around to account for the American format. This did not account for the fact that the month could be set as NaN depending on what the day was (example: June 24th, 2014 written as 6/24/2014 would be interpreted as year: 6, month: NaN, day: 2014). Now, the date parser just recalculates the date entirely, circumventing that issue.
This issue was never present for manually entered dates; those must have been correctly interpreted before being saved to the backend.
=> Fixed date parser for American dates.

app/assets/stylesheets/visualizations.css.scss
Issue #2124 
Edited so vis-title (div which contains the title and subtitle) will only have a width of 70%.
If the text in the title ever exceeds this width, the overflow of text will be hidden.
However, upon hovering over the title, a scroll bar will appear, allowing you to scroll and view the entire title. 
Since the overflow settings are set to auto, the scroll bar will not appear on hover if your title isn't actually overflowing.
=> Long Titles will no longer overflow on Visualization Page

app/assets/javascripts/visualizations/highvis/map.coffee
For #2201.
If the user clicked away from the map before the listener fired, it would still fire anyway and cause the page to get messed up. Removing the listener on end() fixes it.
=> Double canvas issue fixed

app/controllers/data_sets_controller.rb, app/controllers/visualizations_controller.rb
For #2136.
The issue was that the data_sets_controller was redirecting failed updates to the edit page, instead of where the request came from.
The vis page had a similar issue, which is also fixed here.
=> Renaming a Data set or Visualization with a name longer than 128 characters no longer redirects to a broken page.

app/assets/stylesheets/visualizations.css.scss
For #2425.
The Edit Title form used to be too long on Chrome and pretty short on other browsers. Now it takes up 50% of the width of its parent container.
=> Edit title box on vis page is now correct width.

app/assets/javascripts/visualizations/highvis/scatter.coffee
Issue #2457
Made it so that the detailed tool tips would not show hidden fields such as "Group By:", "Number Fields",  "Combined Data Sets", and "Time Period"
=> Removed hidden fields from Scatterplot Detailed Tool Tips

Gemfile, Gemfile.lock, test/test_helper.rb
Using the ruby gem [html5_validator](https://github.com/damian/html5_validator) for testing. Will delete html5check.py when we're sure it's no longer needed. This validator still uses the same backend service but it handles the output correctly even after it broke for us. If we continue to have problems with using an online service, we should look into getting a local service running. For now, tests are passing again.
=> Added ruby gem for HTML validation.

app/assets/javascripts/visualizations/highvis/bar.coffee
Simple fix resolves the issue of borders on bar graphs blocking content by using point padding instead.  [Point padding](http://api.highcharts.com/highcharts/plotOptions.bar.pointPadding) property dynamically manages borders by sizing them as a percentage of the x-axis scale.  As more data points are added, the scale shrinks and so do the spacing.  With the border property, spacing was static.
Also, the line y=0 is colored where a bar of height 0 or close to 0 lies.  This way, tool tips still show up without the borders there.
=> Separates bars by dynamic padding rather than fixed borders

app/views/projects/index.html.erb
For #2484.
Auto-focuses the text entry field after pressing the Create Project fab.
=> Text field is auto-focused when creating project

app/assets/javascripts/visualizations/highvis/bar.coffee
For #2478.
The bar labels would be placed in the order that you selected fields, while the bars are always placed in numerical order based on ID. Now, the labels are placed in numerical order as well.
=> Bar vis x-axis labels are assigned correctly

app/assets/javascripts/visualizations/highvis/scatter.coffee
For #2482.
Regression tooltips were broken in an earlier update.
=> Regression tooltips have been restored.

app/assets/javascripts/data_sets/editTable.js.coffee, app/assets/stylesheets/data_sets.css.scss
For #2477.
The Manual entry box no longer has an unnecessary amount of whitespace at the bottom of the grid.
=> Removed excessive whitespace on manual entry box.

app/assets/stylesheets/visualizations.css.scss
For #2502.
I reduced the icon size slightly, but what was taking up more room was the padding on the icons, so I reduced that considerably on the mobile view.
=> Changed the size of the vis tabs for mobile

app/views/tutorials/_form.html.erb
For #2517.
Before, the default category option when editing a tutorial was always "Getting Started", which could cause you to inadvertently change the category when saving.
=> Default category option in edit tutorials set correctly

app/views/home/create_issue.html.erb
For #2508.
Before, it would just say "Macintosh" or, in the case of Ubuntu 16.04, it would say "X11". Now it should be a bit more accurate, but it isn't perfect (Ubuntu now lists as Linux x86_64; it's not possible for it to say Ubuntu).
=> Auto-detected OS in bug report is more accurate.

app/assets/stylesheets/application.css.scss
There is a width range for which the text on one button wraps and the other doesn't, resulting in differing heights for the buttons, but the text now wraps properly regardless of page width.
=> Fixed CSS so text properly wraps in bug report buttons

app/assets/javascripts/visualizations/highvis/bar.coffee
The best way to do this would be to use the maxPointWidth parameter, but that was added in Highcharts v4.1.8 (we're currently using v4.1.5). Instead, I've used dynamically-calculated pointPadding to restrict bars to a certain width. By the nature of these charts, the more bars there are, the more skinny they are, and the less bars there are, the wider they are. This fix makes sure that when going to fewer than six bars, the bars do not get any bigger, they stay the width that they would be if there were six bars.
=> Added max width to bar chart bars

app/assets/javascripts/visualizations/highvis/bar.coffee, app/assets/javascripts/visualizations/highvis/baseVis.coffee.erb, app/assets/javascripts/visualizations/highvis/highmodifiers.coffee, doc/release.rb
For issue #2547 
- Error bars simply indicate the positions of plus and minus one standard deviation.  Since standard deviation is not the same as error, the option is now called "Mean with Deviation" and the tooltip reflects appropriately.
- There was a small error in the formula for standard deviation in error bars.  It is fixed to be consistent with the Summary tab.
=> Corrects StdDev formula and tooltip for error bars

app/controllers/contrib_keys_controller.rb
For issues #2491 and #2490 
On failure to create a contributor key, the user is redirected to the edit project page (same page they were on) and one error is flashed alerting the user that the key was not created and a list follows with the specific reasons why.
=> Fixed redirect for failed contributor key creation

app/assets/javascripts/visualizations/highvis/highmodifiers.coffee, app/assets/javascripts/visualizations/highvis/pie.coffee, app/controllers/visualizations_controller.rb
Allows the user to view a pie chart for a dataset without user-defined number fields, but restricts them to the row count analysis type. Issue #2561
=> Allow pie charts for datasets without number fields

app/assets/javascripts/visualizations/highvis/histogram.coffee
For #1470 and #2555
Clearer tooltips for histograms, including range feature and displays count instead of value in the case where histogram blocks are consolidated because bins are large compared to amount of data points.
Note: whether the bins are consolidated is determined based on whether they have a value defined for them
=> Clearer tooltips with no "undefined"s

test/functional/sessions_controller_test.rb, test/functional/users_controller_test.rb, test/functional/visualizations_controller_test.rb
This should have been done a while ago. Oops.
This also skips the test that is failing for everyone on Circle. We can debug why it was failing later, but it looks like something to do with ImageMagick.
=> Remove skipped tests

app/controllers/projects_controller.rb, app/controllers/visualizations_controller.rb, app/models/data_set.rb, app/models/project.rb
#2578
The features used here are includes, inverse_of, and pluck.
- Includes is used to prevent 1+N queries. In this case each DataSet was making a separate query its user.
- Inverse_of helps ActiveRecord reuse existing objects. So in this case the project object will be the same as data_set.project.
- Pluck is an efficient way to return just the value of one field.
On my local instance of iSENSE it reduced a call to /api/v1/projects/1?recur=true request with 608 datasets from 3500ms to around 550ms. 
Most of the extra queries were hitting the query cache, however even hitting the cache takes extra time especially when it results in creating a new model object.
=> Use features of active record to reduce queries

Gemfile.lock, app/assets/javascripts/visualizations/highvis/bar.coffee
Fixed bug #2580 
Default sorting is by name; I elaborated on that sort to make it case insensitive.  Results look something like the following:
=> Sort-by-name case sensitivity

Gemfile.lock, app/assets/javascripts/visualizations/highvis/bar.coffee
Fixed bug #2582 
StdDev was calculated manually instead of with the standard function in a different file, so I fixed that; also, I added the standard deviation to the bar tooltip, and tried to improve the error bar tooltip as well.  Pictures attached below.
=> Show standard deviation on bar mean with error tooltip

app/assets/javascripts/visualizations/highvis/bar.coffee
This is a fix for the pull request I made for this bug: #2582 
The standard deviation bounds were being reported incorrectly
=> Fixed weird stdDev bounds issue

app/assets/javascripts/visualizations/highvis/histogram.coffee
This was a fix for bug #2549 
Basically, I added a few lines of code such that the border around bars remain white if there are less than 100 bars per bin, but otherwise the border color changes to match that of the fill for each bar; otherwise, the histogram is eventually reduced to a big white bar, or a largely white bar with only a few meaningless lines of color.
Here are a few pictures, the first demonstrating a histogram just below the threshold (99 bars), and the second above the threshold (more than 100 bars):
=> Histogram boxes get too small

app/assets/javascripts/home/index.js.coffee, app/assets/javascripts/projects/index.js.coffee, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/projects.css.scss, app/views/shared/_project_box.html.erb
For #2613.
To fix the occlusion issue, I just made the project boxes a bit taller. In addition to that, I also restyled the tags so that each tag is its own button that can be clicked to search for that tag. If there are too many tags in the box, the excess will be hidden and a toggle button is added to show and hide those tags.
=> 2613 tag visual upgrade

.rubocop.yml, app/controllers/visualizations_controller.rb, app/models/data_set.rb, config/locales/en.yml, db/migrate/20160922171344_add_counters_to_users.rb, db/migrate/20170403144606_add_count_to_data_sets.rb, db/schema.rb, test/integration/api_v1_test.rb
For #2606.
Users may now only visualize 100000 data points at a time, and upload a maximum of 100000 data points in each data set. Any more than that and the vis page starts to become unusable with so many data points to parse through, not to mention the strain it puts on the servers.
=> Added count to DataSet model

app/controllers/users_controller.rb, app/views/projects/show.html.erb, app/views/users/index.html.erb, config/routes.rb
For #2670 
- Admins can now "Delete Selected" data sets belonging to other users (but will NEVER do so without user permission or very good reason (eg, offensive, breaking the site, user no longer exists...)
- Admins can now "Confirm" users themselves
=> More functionality for admins

app/assets/javascripts/visualizations/highvis/annotations.coffee.erb
Callout bubbles which were right at the edge were not able to be hidden by hovering.  This is now fixed.
=> Resolve issue with callout hovering

app/views/tutorials/index.html.erb
By adding the tag "?rel=0" to the end of the URLs we avoid annoying recommendations.
=> Tutorials - avoid youtube recommendations

app/assets/javascripts/visualizations/highvis/bar.coffee
Fixes bug #2716. Simply removes code snippet that updates the drop-down based on the current y-axis selections. Now the sort-by does not change from the default unless manually changed.
=> Fix discrepancy between sort-by drop-down and actual sorting

app/assets/javascripts/visualizations/highvis/highmodifiers.coffee
Use different stdev formula as Fred requested - see [Wikipedia](https://en.wikipedia.org/wiki/Standard_deviation#Sample_standard_deviation_of_metabolic_rate_of_Northern_Fulmars) for details... we want to switch from *actual* stdev to *sample* stdev.
"For #2736 "
=> Use sample standard deviation

app/mailers/user_mailer.rb, test/fixtures/user_mailer/report_content_email.html, test/functional/home_controller_test.rb, test/unit/user_mailer_test.rb
When merging via github for #2790 , I took out an `end` keyword by mistake.
=> Missing end from merge conflict + adding test cases

app/controllers/subscriber_emails_controller.rb, app/views/layouts/application.html.erb, app/views/subscriber_emails/index.html.erb, app/views/subscriber_emails/new.html.erb, app/views/subscriber_emails/show.html.erb, config/routes.rb
Added a page to view all subscriber emails (Replaced the old top layout Subscriber Emails link - will now take you to the list of subscriber emails instead of the form to create one)
On the list page, you can click on "Click here to create and send an email" to create an email and send it. Also, you can click on the email subject to go to a page to view the subject, message, and date created of the email.
=> [Dn2648] List for Subscriber Emails

app/controllers/users_controller.rb, app/mailers/user_mailer.rb, test/fixtures/users.yml, test/unit/user_test.rb
I guess there was an old unused form of what we now use as confirmation via Devise.
References in the code are not needed.
Migration to follow...
=> Remove vestigial validation

config/application.rb, config/environment-variables.yml
NOTE: it may be required to run `RAILS_ENV=production bundle exec rake assets:precompile` to precompile assets before starting the server.
I added a section to the `config/application.rb` to load environment variables (including `RAILS_ENV` and `RACK_ENV`, which can be set to 'production') from the new `environment-variables.yml` file I made.
Then contents of `environment-variables.yml` is not available on this GitHub for security reasons.
=> 2024-02-08 - nat | enable production mode for server
